### ISSUE TITLE
vscode bpmn editor sometimes doesn't save file after longer sessions of editing with no errors or warnings.

### ISSUE THREAD

**Issue by mikewodarczyk** [kiegroup/kie-tooling-store#33] opened 2021-02-03 19:32 UTC
I have used the bpmn extension to edit a few diagrams so far.  On the 2 occasions where I used the editor for mode than 30 minutes doing lot of edits, additions, deletes, movement of objects, etc, I try to use File -> Save to save a copy of my work.  VS code doesn't react at all.  The file is not marked as saved in vscode. The filesystem shows an old timestamp on the file.

I then try File -> Save As.  I navigate to a local folder and give the file a name and click ok.  Still the file does not get marked as saved and a file is not created at the location I am saving to.  I have full permissions on the folder.

Is there any place I can look for an error message or process dump of what is going on to help you (or me) understand why the file is not being saved?

**Comment by caponetto** [comment] 2021-02-04 13:40
Hi @mikewodarczyk, thanks for dedicating some time to help us with feedback. We really appreciate it!

By the description you've provided, it looks like your diagram got somehow invalid, thus cannot be saved.
This could happen when, for example, an arrow is not connected to a component.
Currently, we don't have a notification mechanism to warn users, but this is something that we are working on!
We actually have an open [JIRA ticket](https://issues.redhat.com/browse/KOGITO-2101) for cases like this.

So, to help me understand if my assumption is correct,
could you please check if there are exceptions in the _Webview Developer Tools_ console when you try to save your file?
(Go to View -> Command Pallete -> search for "_open webview developer Tools_").

I'm attaching a gif showing how to do it.
![Peek 2021-02-04 10-27](https://user-images.githubusercontent.com/638737/106899982-bf173080-66d4-11eb-84fe-766627a14f96.gif)

**Comment by ederign** [comment] 2021-02-16 16:56
@caponetto I saw a similar issue happening on VS Code on Adriel's Kie live. (around 50 mins)

**Comment by tiagobento** [comment] 2021-05-04 18:30
Closing as we don't have a consistent reproducer. Please feel free to reopen this issue in case we have new information.

**Closed as completed by tiagobento** 2021-05-04 18:30 UTC
